//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suporte.Controles.Forms.ConstrutorDeFormula.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suporte.Controles.Forms.ConstrutorDeFormula.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BotaoAgrupadorDireito {
            get {
                object obj = ResourceManager.GetObject("BotaoAgrupadorDireito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoAgrupadorEsquerdo {
            get {
                object obj = ResourceManager.GetObject("BotaoAgrupadorEsquerdo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoCursor {
            get {
                object obj = ResourceManager.GetObject("BotaoCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito0 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito1 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito2 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito3 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito4 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito5 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito6 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito7 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito8 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigito9 {
            get {
                object obj = ResourceManager.GetObject("BotaoDigito9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigitoPontoVirgula {
            get {
                object obj = ResourceManager.GetObject("BotaoDigitoPontoVirgula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoDigitoVirgula {
            get {
                object obj = ResourceManager.GetObject("BotaoDigitoVirgula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoOperadorAdicao {
            get {
                object obj = ResourceManager.GetObject("BotaoOperadorAdicao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoOperadorDivisao {
            get {
                object obj = ResourceManager.GetObject("BotaoOperadorDivisao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoOperadorMultiplicacao {
            get {
                object obj = ResourceManager.GetObject("BotaoOperadorMultiplicacao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotaoOperadorSubtracao {
            get {
                object obj = ResourceManager.GetObject("BotaoOperadorSubtracao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
